from __future__ import annotations

from collections.abc import Generator, Sequence

from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any, cast, overload
from uuid import NAMESPACE_URL, UUID, uuid5
from urllib.parse import ParseResult, urlencode, urlunparse

import usb.core
from usb.backend import libusb1

if TYPE_CHECKING:
    from usb.backend.libusb1 import _LibUSB

libusb_backend: _LibUSB


def _resolve_backend() ->_LibUSB:
    libusb_backend: _LibUSB | None

    try:
        import libusb_package  # type: ignore[import-not-found]  # pyright: ignore[reportMissingImports]
        libusb_backend = cast(Any, libusb_package.get_libusb1_backend())
    except ImportError:
        libusb_backend = None


    if libusb_backend is None:
        libusb_backend = libusb1.get_backend()
        if libusb_backend is None:
            raise RuntimeError(
                'Cannot use libusb1 backend. Make sure libusb 1.x is installed ' +
                'properly if you installed it manually, or reinstall ' +
                'besta-tools with the [prebuilt-libusb] option.'
            )
    return libusb_backend


libusb_backend = _resolve_backend()


@dataclass
class DfuType:
    name: str
    description: str
    vid: int
    pid: int
    manufacturer: str
    product: str
    supported: bool = field(default=True)

    def uuid5(self) -> UUID:
        url = urlunparse(ParseResult(
            scheme='usb',
            netloc='',
            path='',
            params='',
            query=urlencode([
                ('vid', f'{self.vid:04x}'),
                ('pid', f'{self.pid:04x}'),
                ('manufacturer', self.manufacturer),
                ('product', self.product),
            ]),
            fragment='',
        ))
        return uuid5(NAMESPACE_URL, url)

    def emit_udev_rule(self) -> str:
        return (
            f'# {self.description}\n'
            f'SUBSYSTEM=="usb", ATTR{{idVendor}}=="{self.vid:04x}", ATTR{{idProduct}}=="{self.pid:04x}", '
            f'ATTR{{manufacturer}}=="{self.manufacturer}", ATTR{{product}}=="{self.product}", TAG+="uaccess"\n'
            f'DRIVER=="usb-storage", ACTION=="add", ATTRS{{idVendor}}=="{self.vid:04x}", ATTRS{{idProduct}}=="{self.pid:04x}", '
            f'ATTRS{{manufacturer}}=="{self.manufacturer}", ATTRS{{product}}=="{self.product}", '
            f'RUN+="/bin/sh -c \'echo -n $kernel > $sys$devpath/driver/unbind\'"'
        )

    def emit_zadig_cfg(self) -> str:
        return (
            '[device]\n' +
            f'  Description = "{self.description.replace('"', '_')}"\n' +
            f'  VID = 0x{self.vid:04X}\n' +
            f'  PID = 0x{self.pid:04X}\n' +
            f'  GUID = "{{{str(self.uuid5()).upper()}}}"\n'
        )


KNOWN_DEVICE_TYPES: Sequence[DfuType] = (
    DfuType(
        name='tlcs900',
        description='TLCS-900 family bootloader',
        vid=0x0537,
        pid=0xa703,
        manufacturer='Removable',
        product='UDisk',
    ),
    DfuType(
        name='s3c',
        description='S3C2416 family bootloader',
        vid=0x054b,
        pid=0x1582,
        manufacturer='SAMSUNG',
        product='S3C2443',
    ),
    DfuType(
        name='imx233',
        description='iMX233 family bootloader',
        vid=0x0419,
        pid=0x0133,
        manufacturer='Besta',
        product='UDisk',
    ),
    DfuType(
        name='w55pa71',
        description='Nuvoton W55PA71 family bootloader',
        vid=0x0417,
        pid=0x9394,
        manufacturer='Winbond      ',
        product='W55PA71      ',
    ),
    DfuType(
        name='n32926',
        description='Nuvoton N32926 family bootloader',
        vid=0x0483,
        pid=0x5720,
        manufacturer='nuvoTon',
        product='USB MSC',
        supported=False,
    ),
)

KNOWN_DEVICE_INDEX: dict[tuple[int | None, int | None, str | None, str | None], DfuType] = {
    (dev.vid, dev.pid, dev.manufacturer, dev.product): dev for dev in KNOWN_DEVICE_TYPES
}


def generate_udev_file(path: Path) -> None:
    with path.open('w') as udev_file:
        udev_file.write('# Generated by dfutool from besta-tools\n\n')
        for dev_type in KNOWN_DEVICE_TYPES:
            udev_file.write(dev_type.emit_udev_rule())
            udev_file.write('\n')

def generate_zadig_files(path: Path) -> None:
    path.mkdir(exist_ok=True)

    for dev_type in KNOWN_DEVICE_TYPES:
        output_path = path / f'{dev_type.name}.cfg'
        with output_path.open('w') as output_file:
            output_file.write(dev_type.emit_zadig_cfg())


@overload
def trim_nul_terminated(value: None) -> None: ...
@overload
def trim_nul_terminated(value: str) -> str: ...
@overload
def trim_nul_terminated(value: str | None) -> str | None: ...
def trim_nul_terminated(value: str | None) -> str | None:
    if value is None:
        return None
    first_zero = value.find('\x00')
    if first_zero == -1:
        return value
    return value[:first_zero]


def enumerate_device() -> Generator[tuple[DfuType, usb.core.Device]]:
    for dev in usb.core.find(find_all=True, backend=libusb_backend):
        try:
            device_type_key = (
                dev.idVendor,
                dev.idProduct,
                trim_nul_terminated(dev.manufacturer),
                trim_nul_terminated(dev.product)
            )
            if device_type_key in KNOWN_DEVICE_INDEX:
                devtype = KNOWN_DEVICE_INDEX[device_type_key]
                if devtype.supported:
                    yield devtype, dev
        except ValueError:
            # No langid and probably no access to device. Skipping,
            continue
